### ISSUE TITLE
Move code from edx-platform/openedx/core/apidoc.py to edx-drf-extensions

### ISSUE THREAD

**Issue by nedbat** [edx/api-doc-tools#1]
Some bits may stay in edx-platform if they are truly specific to edx-platform.

**Comment by kdmccormick** [comment]
(In progress)

**Comment by kdmccormick** [comment]
See https://github.com/edx/api-doc-tools/pull/13

**Comment by kdmccormick** [comment]
Now that #13 has merged, this issue is complete.

Next, in #11, we will cut a release and install it into https://github.com/edx/edx-platform.

**Comment by kdmccormick** [comment]
Now that #13 has merged, this issue is complete.

Next, in #11, we will cut a release and install it into https://github.com/edx/edx-platform.
