### ISSUE TITLE
support for APIs that are not in /api/

### ISSUE THREAD

**Issue by morenol** [edx/api-doc-tools#27]
I wanted to add this dependency to edx-analytics-data-api in https://github.com/edx/edx-analytics-data-api/pull/329, but some of the APIs there are not in the root path `/api`, for instance there are some APIs under /enterprise/api/ that are taken from https://github.com/edx/edx-enterprise-data

How should I do that?

 I think that we could make that the [ApiSchemaGenerator](https://github.com/edx/api-doc-tools/blob/b6c61b9785aeab3f355d76ada783d8dbe4aeec9e/edx_api_doc_tools/conf_utils.py#L153) takes the root path from the django settings or as a parameter passed when it is being instantiated. 

What do you think?

**Comment by kdmccormick** [comment]
+1

I have the opposite problem of you: I want to make the root path of a service to be `/api/v2` in order to exclude all our deprecated endpoints under `/api/v1`.

For both our cases, it'd be great to make the root in `ApiSchemaGenerator` more easily configurable.
